### ISSUE TITLE
Swift - Import

### ISSUE THREAD

**Issue by AngeloGiurano** [atljeremy/JFMinimalNotifications#18]
Can I use this pod with Swift?
I've tried both: 

import JFMinimalNotification  
import JFMinimalNotifications 

but it says that can not find such a module.
Of course everything after installing the pod.
Is it possible to install the pod and use it with Swift or not yet and I should manually import all files and mix'n match?

Thanks :)

**Comment by atljeremy** [comment]
I've not personally tried using the pod with Swift. If you want to use it now I'd suggest just cloning the source and adding directly to your project with a bringing header to expose it to Swift.

Note: I'm actually going to start converting this library to Swift soon so once that is done it should be much easier to use the pod with Swift.

**Comment by AngeloGiurano** [comment]
Thanks a lot for the fast response, I'll clone it and wait for the Swift conversion
