### ISSUE TITLE
No property called "edgePadding"

### ISSUE THREAD

**Issue by backmeupplz** [atljeremy/JFMinimalNotifications#19]
Hello! Thank you a lot for this element!

But how to set  edge padding now? I can't see this property.

self.minimalNotification.edgePadding = UIEdgeInsetsMake(0, 0, 10, 0);

Thanks in advance

**Comment by atljeremy** [comment]
Sorry, I've not pushed an update to CocoaPods with that update just yet. If you grab the latest ha from the master branch it's there https://github.com/atljeremy/JFMinimalNotifications/blob/master/JFMinimalNotification/JFMinimalNotification.h#L85

I'll try to get a new cocoa pods version out tomorrow

**Comment by backmeupplz** [comment]
Thanks!

**Comment by atljeremy** [comment]
@backmeupplz JFMinimalNotifications v0.0.5 has been published to CocoaPods https://cocoapods.org/pods/JFMinimalNotifications
