### ISSUE TITLE
Looks like "setLeftAccessoryView" works only after notification is shown

### ISSUE THREAD

**Issue by backmeupplz** [atljeremy/JFMinimalNotifications#20]
Hello again!

I'm trying to get rid of left accessory view (i.e. setLeftAccessoryView to nil). I'm doing that before I show notification, but it works only on touch block.
```
notification = JFMinimalNotification(style: .StyleInfo, title: "Some title'", subTitle: "Subtitle", dismissalDelay: 5.0, touchHandler: { () -> Void in
            self.notification.setLeftAccessoryView(nil, animated: false)
        })
        view.addSubview(notification)
        notification.show()
```
^^^ this works and left accessory view is removed upon touching the notification
```
notification = JFMinimalNotification(style: .StyleInfo, title: "Som etit;e'", subTitle: "Subtitle", dismissalDelay: 5.0, touchHandler: { () -> Void in
        })
        view.addSubview(notification)
        self.notification.setLeftAccessoryView(nil, animated: false)
        notification.show()
```
^^^ this doesn't work :( left accessory is still there.

**Comment by atljeremy** [comment]
Hey!

I've not tested this but give this a try...

```swift
self.notification = JFMinimalNotification(style: .StyleInfo, title: "Som title'", subTitle: "Subtitle", dismissalDelay: 5.0, touchHandler: { () -> Void in
})
view.addSubview(notification)
self.notification.setLeftAccessoryView(nil, animated: false)
self.notification.layoutIfNeeded() // <- adding this. Again, I'm not sure if this will fix it or not but give it a shot and let me know
notification.show()
```

**Comment by backmeupplz** [comment]
Didn't work :(

**Comment by atljeremy** [comment]
OK, gonna have to create a new swift project and try it out myself. give me a bit and I'll get back to you.

**Comment by backmeupplz** [comment]
Looks like 
`- (void)setStyle:(JFMinimalNotificationStytle)style animated:(BOOL)animated` 
is called after I call 
`self.notification.setLeftAccessoryView(nil, animated: false)`
as if I comment out 
`[self setLeftAccessoryView:self.accessoryView animated:animated];`
in that method, everything works well.

**Comment by atljeremy** [comment]
OK coo, probably a mucked up order of operations then. Thanks for the tip. I'll dig in and get a fix for this.

**Comment by backmeupplz** [comment]
Thank you!

**Comment by atljeremy** [comment]
@backmeupplz JFMinimalNotifications v0.0.5 has been published to CocoaPods https://cocoapods.org/pods/JFMinimalNotifications

**Comment by atljeremy** [comment]
Closed accidentally. Re-opened.

**Comment by valzevul** [comment]
Hi @backmeupplz,

I was able to fix the problem by using a delegate:
```
extension ViewController: JFMinimalNotificationDelegate {
  
  func minimalNotificationWillShowNotification(notification: JFMinimalNotification!) {
    minimalNotification.setLeftAccessoryView(nil, animated: false)
    minimalNotification.layoutIfNeeded()
  }
}
```

Seems like it works almost for all required cases.

**Comment by bawn** [comment]
@valzevul 
It's work

**Comment by bawn** [comment]
@valzevul It doesn't work sometime

**Comment by atljeremy** [comment]
@backmeupplz @valzevul @bawn 
I just release v0.0.7 to CocoaPods https://cocoapods.org/pods/JFMinimalNotifications
It's also available in the Releases tab here https://github.com/atljeremy/JFMinimalNotifications/releases/tag/0.0.7

With this release there are 3 new styles, they are...

```objective-c
/**
 * @return Used to get a title and subtitle, no accessory views, and white bg with black label text. Use the .bakgroundColor property on the notification to set the desired background color and .textColor property on the titleLabel and subTitleLabel UILabel's to change text color.
 */
JFMinimalNotificationStyleCustom,
    
/**
 * @return A dark blur with vibrancy effect in the bakground with black label text.
 */
JFMinimalNotificationStyleBlurDark,
    
/**
 * @return A light blur with vibrancy effect in the bakground with black label text.
 */
JFMinimalNotificationStyleBlurLight
```

Each of these new styles doesn't show a left or right accessory view by default. So if you want a notification without left or right accessory views you can do something like this...

```objective-c
self.minimalNotification = [JFMinimalNotification notificationWithStyle:JFMinimalNotificationStyleCustom title:self.titleLabelTextField.text subTitle:self.subTitleLabelTextField.text dismissalDelay:0.0 touchHandler:^{
    [self.minimalNotification dismiss];
}];

// Set a custom backgroundColor, default for JFMinimalNotificationStyleCustom is white
self.minimalNotification.background = [UIColor purpleColor];

// Set title and subtitle label text color, default for JFMinimalNotificationStyleCustom is black
self.minimalNotification.titleLabel.textColor = [UIColor whiteColor];
self.minimalNotification.subTitleLabel.textColor = [UIColor whiteColor];
```

With this new update I'm going to close this issue. Setting the left accessoryView to `nil` before showing it isn't the way to show a notification without any accessory views. Use one of the new styles listed above to do so. Thanks!

**Comment by valzevul** [comment]
@atljeremy awesome man, thank you very much!

**Comment by bawn** [comment]
@atljeremy Thanks
