### ISSUE TITLE
Must have a superview before calling show

### ISSUE THREAD

**Issue by LoganWright** [atljeremy/JFMinimalNotifications#27]
This is currently implemented like this:

```ObjC
- (BOOL)isReadyToDisplay
{
    return (BOOL)self.superview;
}
```

Which can have inconsistent and undesired side effects.  While if statements implicitly compare to `nil`, implicit casting behaves differently.

Right now, I'm getting random crashing when it is in fact ready to display.  Should be:

```ObjC
- (BOOL)isReadyToDisplay
{
    return self.superview != nil;
}
```

**Comment by atljeremy** [comment]
@LoganWright This was fixed a few months ago in the master branch. I forgot to release it to cocoa pods though, so I just went ahead and did that. The version is 0.0.6 - https://github.com/atljeremy/JFMinimalNotifications/releases/tag/0.0.6

**Comment by LoganWright** [comment]
Thanks for the update!
