### ISSUE TITLE
creation of notifications without icon

### ISSUE THREAD

**Issue by tryadelion** [atljeremy/JFMinimalNotifications#29]
hello, i'm using the cocoapods version with swift, is there any option to create any of the provided styles ( or a custom one with custom background colour, if possible) without any icon at all ?
I see there are options to show it on the left or on the right, but i can't find one to make the text fill the whole space.

thank you!

(yes, i'm trying to make it look like an android snackbar. :P)

**Comment by atljeremy** [comment]
This is very much the same as https://github.com/atljeremy/JFMinimalNotifications/issues/20 - closing this issue so that I only have open issue related to this. Please monitor https://github.com/atljeremy/JFMinimalNotifications/issues/20 to stay up-to-date and provide feedback on this topic.
