### ISSUE TITLE
Notification being displayed under the tabbar/navigationbar

### ISSUE THREAD

**Issue by EssamEmad** [atljeremy/JFMinimalNotifications#33]
Awesome library, but I had one issue. When I display the notification in a TabbarViewController the notification gets displayed under the tabbar. I also tried adding it to the tableview instead of the parent view, it didn't get dismissed automatically although I added the dismissalDelay parameter.

**Comment by Black-Colt** [comment]
I think thats why you have edgePadding:

In navigation controller you need to add his height and 15 Like this:
    self.minimalNotification.edgePadding = UIEdgeInsetsMake(self.navigationController.navigationBar.frame.size.height + 15, 0, 0, 0);

**Comment by atljeremy** [comment]
Yep, adding additional `edgePadding` should address your issue @EssamEmad
