### ISSUE TITLE
iOS 10 show issue

### ISSUE THREAD

**Issue by bryanGoRoD** [atljeremy/JFMinimalNotifications#34]
Hi, animation for show and dismiss are broken for iOS 10.

**Comment by atljeremy** [comment]
Thanks for the heads up. I'll take a look and update as needed.

**Comment by algrid** [comment]
Hi, I added a PR fixing show/dismiss animations.

**Comment by atljeremy** [comment]
This has been address in this PR: https://github.com/atljeremy/JFMinimalNotifications/pull/35
I'll create a new release with this fix today.
