### ISSUE TITLE
Have the default icons align right?

### ISSUE THREAD

**Issue by tamiof** [atljeremy/JFMinimalNotifications#4]
Hey, I absolutely love this library. Very very well done.

I read a previous issue and about aligning right and had the title and subtitle aligned successfully.
Is there any way I can show the icons marking success, error etc align right also? That would be perfect.

Thanks

**Comment by atljeremy** [comment]
That shouldn't be hard to achieve. Let me get that added in and I'll get back to you ASAP. 

-Jeremy

**Comment by tamiof** [comment]
That was the quickest reply in github history.
You're awesome

**Comment by atljeremy** [comment]
OK, I've created a new branch called `align_right` (https://github.com/atljeremy/JFMinimalNotifications/tree/align_right). This branch defaults the icons for checkmark, error, info, warning, etc to the right. It was a one update to make this happen. I'll work on adding in a configuration option to make this an official part of the control in the next release, which should be soon. For now though, you can use the branch above. Here's a screen shot showing it working...

![ios simulator screen shot jan 2 2015 9 11 10 pm](https://cloud.githubusercontent.com/assets/1019253/5601296/e8dc80f4-92c4-11e4-9375-02372409f13e.png)

**Comment by tamiof** [comment]
This is glorious! Works like a charm.
Thank you so much
