### ISSUE TITLE
Notifications fail to show / hide

### ISSUE THREAD

**Issue by kookiekrak** [atljeremy/JFMinimalNotifications#6]
I'm seeing issues trying to use these notifications on a basic Master-Detail template.

The notifications will show up in the wrong position on the table view and won't dismiss.

In addition, I tried:
-- attaching the notification to the navigation controller
-- attaching the notification to the window
-- overlaying a clear UIView across the whole screen and attaching the notification to that

 but unfortunately nothing shows up then.

Thanks for making this, really excited to use it!

**Comment by atljeremy** [comment]
Let me try to reproduce the issue. If I can reproduce I'll see what I can do about addressing it. If not, I'll have to ask that you provide me with an example project demonstrating the issue. I'll keep you posted.

-Jeremy

**Comment by kookiekrak** [comment]
https://github.com/kookiekrak/SampleMasterDetail

added one here
![ios simulator screen shot jan 7 2015 3 01 47 pm](https://cloud.githubusercontent.com/assets/585120/5655017/2d5c01c0-967e-11e4-8aa9-303d678db0d4.png)

**Comment by atljeremy** [comment]
I was abel to get it working just fine in this project: https://www.dropbox.com/sh/rmqpy97vo1hrb2u/AADVaP56ohXLXm1-lP6TUqpHa?dl=0

Let me know if this helps.

**Comment by kookiekrak** [comment]
Awesome! got it to work now. I have it as an instance variable and i use show and dismiss instead of creating it repeatedly.

Thanks for the help!

**Comment by atljeremy** [comment]
No problem, glad you got it working.
