### ISSUE TITLE
Non-public API Error

### ISSUE THREAD

**Issue by sametgultekin** [atljeremy/JFMinimalNotifications#9]
When i  try to submit the app i get non-public api error:

>The app references non-public selectors in Payload ...... didDismissNotification:

**Comment by atljeremy** [comment]
Strange, I'm not using any private API's that I know of. I'll take a look today and get a fix in ASAP based on what I find.

-Jeremy

**Comment by atljeremy** [comment]
So I've tested this for myself and I can confirm that ipa validation does "warn" about the `JFMinimalNotificationDelegate` method named `didDismissNotification`. There must be a matching method in the iOS SDK somewhere that it thinks is being used. This is obviously not the case and will likely not result in app being rejected. Again, this is not an "error" as you reported, it's a "warning".

I will update the delegate methods to a more unique name to ensure this warning goes away.

**Comment by atljeremy** [comment]
This is fixed in the master branch as of commit https://github.com/atljeremy/JFMinimalNotifications/commit/f4af01a2e4023b88ac5eb9e4eb02652c6d6ba504
